const $=s=>document.querySelector(s);const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let state={name:localStorage.getItem('skillos-name')||'',view:'dashboard',selected:null,skills:load('skillos-skills',[]),session:null};
const esc=s=>(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mins=n=>`${Math.floor((n||0)/60)}h ${String((n||0)%60).padStart(2,'0')}m`;const persist=()=>save('skillos-skills',state.skills);
function layout(content){return `<div class="shell"><aside class="side"><div class="brand"><div class="logo">S</div><div><b>SKILLOS</b><div class="muted">EVOLUCAO INTELIGENTE</div></div></div><div class="nav">${nav()}</div></aside><main class="main">${content}</main><div class="bottom">${nav()}</div></div>`}
function nav(){return [['dashboard','Inicio'],['skills','Competencias'],['time','Tempo'],['analytics','Analytics']].map(([v,l])=>`<button data-nav="${v}" class="${state.view===v?'active':''}">${l}</button>`).join('')}
function render(){if(!state.name){$('#app').innerHTML=`<div class="login"><div class="card"><div class="logo">S</div><h1>SKILLOS</h1><p class="muted">O teu sistema pessoal de desenvolvimento de competencias.</p><form id="login"><div class="field"><label>O teu nome</label><input id="name" required placeholder="Ex.: Bedi"></div><button class="btn">Entrar</button></form></div></div>`;$('#login').onsubmit=e=>{e.preventDefault();state.name=$('#name').value.trim();localStorage.setItem('skillos-name',state.name);render()};return}if(state.selected){detail();return}let c=state.view==='dashboard'?dashboard():state.view==='skills'?skillsPage():state.view==='time'?timePage():analytics();$('#app').innerHTML=layout(c);bindCommon()}
function dashboard(){let total=state.skills.reduce((a,s)=>a+(s.minutes||0),0);return `<div class="top"><div><div class="muted">O teu espaco de evolucao</div><h1>Ola, ${esc(state.name)}</h1></div><button class="btn" id="new">+ Nova competencia</button></div><div class="grid"><div class="card stat"><div class="muted">Competencias</div><strong>${state.skills.length}</strong></div><div class="card stat"><div class="muted">Tempo total</div><strong>${mins(total)}</strong></div><div class="card stat"><div class="muted">Temas concluidos</div><strong>${state.skills.reduce((a,s)=>a+(s.topics||[]).filter(x=>x.done).length,0)}</strong></div><div class="card stat"><div class="muted">Sessoes</div><strong>${state.skills.reduce((a,s)=>a+(s.sessions||[]).length,0)}</strong></div></div><h2>Competencias em desenvolvimento</h2>${cards()}<div class="card"><h3>IA do SKILLOS</h3><p class="muted">Abre uma competencia e usa a aba IA para obter roadmap, tutoria e analise contextual.</p></div>`}
function cards(){return state.skills.length?`<div class="grid two">${state.skills.map(s=>`<div class="card skill" data-open="${s.id}"><div class="muted">${esc(s.current)} → ${esc(s.target)}</div><h3>${esc(s.name)}</h3><p>${esc(s.objective)}</p><div class="progress"><span style="width:${s.progress||0}%"></span></div><p class="muted">${s.progress||0}% · ${mins(s.minutes)}</p></div>`).join('')}</div>`:`<div class="card"><p>Ainda nao tens competencias.</p><button id="new" class="btn">Criar a primeira</button></div>`}
function skillsPage(){return `<div class="top"><div><h1>Competencias</h1><p class="muted">A entidade central do SKILLOS.</p></div><button id="new" class="btn">+ Nova</button></div>${cards()}`}
function timePage(){let sessions=state.skills.flatMap(s=>(s.sessions||[]).map(x=>({...x,skill:s.name}))).sort((a,b)=>b.date.localeCompare(a.date));return `<h1>Gestao de Tempo</h1><div class="card">${sessions.length?sessions.map(x=>`<div class="item"><div class="title"><b>${esc(x.skill)}</b><div class="muted">${esc(x.topic)} · ${new Date(x.date).toLocaleString('pt-PT')}</div></div><b>${mins(x.minutes)}</b></div>`).join(''):'Nenhuma sessao registada.'}</div>`}
function analytics(){return `<h1>Analytics</h1><div class="grid two">${state.skills.map(s=>`<div class="card"><h3>${esc(s.name)}</h3><div class="progress"><span style="width:${s.progress||0}%"></span></div><p>${s.progress||0}% · ${mins(s.minutes)} · ${(s.sessions||[]).length} sessoes</p></div>`).join('')}</div>`}
function form(skill={}){let f={name:'',objective:'',current:'Basico',target:'Avancado',weeklyHours:5,targetDate:'',...skill};showModal(`<h2>${skill.id?'Editar':'Nova'} competencia</h2><form id="skillForm"><div class="field"><label>Nome</label><input name="name" required value="${esc(f.name)}"></div><div class="field"><label>Objetivo</label><textarea name="objective" required>${esc(f.objective)}</textarea></div><div class="row"><div class="field"><label>Nivel atual</label><select name="current">${['Iniciante','Basico','Intermedio','Avancado'].map(x=>`<option ${f.current===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Nivel desejado</label><select name="target">${['Basico','Intermedio','Avancado','Especialista'].map(x=>`<option ${f.target===x?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="row"><div class="field"><label>Horas/semana</label><input name="weeklyHours" type="number" min="1" value="${f.weeklyHours}"></div><div class="field"><label>Prazo</label><input name="targetDate" type="date" value="${f.targetDate||''}"></div></div><div class="row"><button type="button" class="btn ghost close">Cancelar</button><button class="btn">Guardar</button></div></form>`);$('#skillForm').onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));d.weeklyHours=+d.weeklyHours;if(skill.id)state.skills=state.skills.map(s=>s.id===skill.id?{...s,...d}:s);else state.skills.push({...d,id:crypto.randomUUID(),minutes:0,progress:0,topics:[],roadmap:[],resources:[],practices:[],assessments:[],sessions:[]});persist();closeModal();render()}}
function detail(){let s=state.skills.find(x=>x.id===state.selected);if(!s){state.selected=null;render();return}$('#app').innerHTML=layout(`<button id="back" class="btn ghost">← Voltar</button><div class="card"><div class="top"><div><div class="muted">${esc(s.current)} → ${esc(s.target)}</div><h1>${esc(s.name)}</h1><p>${esc(s.objective)}</p></div><button id="study" class="btn">▶ Estudar</button></div><div class="progress"><span style="width:${s.progress||0}%"></span></div><p>${s.progress||0}% · ${mins(s.minutes)}</p></div><div class="tabs">${['overview','roadmap','topics','resources','practices','assessments','history','ai'].map((x,i)=>`<button data-tab="${x}" class="${i===0?'active':''}">${['Visao geral','Roadmap','Temas','Recursos','Pratica','Avaliacao','Historico','IA'][i]}</button>`).join('')}</div><div id="tab"></div>`);bindCommon();$('#back').onclick=()=>{state.selected=null;render()};$('#study').onclick=()=>startTimer(s);$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTab(s,b.dataset.tab)});renderTab(s,'overview')}
const $$=s=>[...document.querySelectorAll(s)];
function renderTab(s,t){let el=$('#tab');if(t==='overview'){el.innerHTML=`<div class="grid two"><div class="card"><b>Proximo passo</b><p>${esc((s.topics||[]).find(x=>!x.done)?.title||'Criar o primeiro tema')}</p></div><div class="card"><b>Disponibilidade</b><p>${s.weeklyHours}h por semana</p></div></div>`;return}if(t==='history'){el.innerHTML=`<div class="card">${(s.sessions||[]).length?(s.sessions||[]).slice().reverse().map(x=>`<div class="item"><div class="title"><b>${esc(x.topic)}</b><div class="muted">${new Date(x.date).toLocaleString('pt-PT')}</div></div><b>${mins(x.minutes)}</b></div>`).join(''):'Sem sessoes.'}</div>`;return}if(t==='ai'){s.aiHistory=s.aiHistory||[];el.innerHTML=`<div class="card"><h3>SKILLOS IA</h3><p class="muted">Memória separada para esta competência. A IA propõe; tu decides.</p><div class="field"><label>Especialista</label><select id="aiAction"><option value="architect">Arquiteta de Competências</option><option value="planner">Planeadora</option><option value="tutor">Tutora</option><option value="assessor">Avaliadora</option><option value="analyst">Analista de Progresso</option><option value="coach">Coach</option></select></div><div id="chat" class="chat">${s.aiHistory.map(m=>`<div class="msg ${m.role==='user'?'user':'ai'}">${esc(m.text)}</div>`).join('')}</div><div class="field"><textarea id="question" placeholder="Pergunta, dificuldade ou pedido..."></textarea></div><div class="row"><button id="clearAI" class="btn ghost">Limpar memória</button><button id="askAI" class="btn">Enviar</button></div><div id="aiOut"></div></div>`;$('#askAI').onclick=()=>askAI(s);$('#clearAI').onclick=()=>{if(confirm('Limpar a memória desta competência?')){s.aiHistory=[];s.aiProposal=null;recalc(s);renderTab(s,'ai')}};if(s.aiProposal)showProposal(s,s.aiProposal);return}let labels={roadmap:'Roadmap',topics:'Tema',resources:'Recurso',practices:'Pratica',assessments:'Avaliacao'};let arr=s[t]||[];el.innerHTML=`<div class="card"><div class="row"><input id="draft" placeholder="Adicionar ${labels[t].toLowerCase()}"><button id="add" class="btn">Adicionar</button></div><div id="items">${arr.map(x=>`<div class="item ${x.done?'done':''}"><button class="btn ghost" data-toggle="${x.id}">${x.done?'✓':'○'}</button><span class="title">${esc(x.title)}</span><button class="btn danger" data-del="${x.id}">×</button></div>`).join('')}</div></div>`;$('#add').onclick=()=>{let title=$('#draft').value.trim();if(!title)return;s[t]=[...arr,{id:crypto.randomUUID(),title,done:false}];recalc(s);renderTab(s,t)};$$('[data-toggle]').forEach(b=>b.onclick=()=>{s[t]=arr.map(x=>x.id===b.dataset.toggle?{...x,done:!x.done}:x);recalc(s);renderTab(s,t)});$$('[data-del]').forEach(b=>b.onclick=()=>{s[t]=arr.filter(x=>x.id!==b.dataset.del);recalc(s);renderTab(s,t)})}
function recalc(s){let a=[...(s.topics||[]),...(s.practices||[]),...(s.assessments||[])];s.progress=a.length?Math.round(a.filter(x=>x.done).length/a.length*100):s.progress;state.skills=state.skills.map(x=>x.id===s.id?s:x);persist()}
function startTimer(s){let seconds=0,running=true;showModal(`<h2>${esc(s.name)}</h2><p class="muted">Sessao livre</p><div id="clock" class="timer">00:00</div><div class="row"><button id="pause" class="btn ghost">Pausar</button><button id="finish" class="btn">Concluir</button></div>`);let id=setInterval(()=>{if(running){seconds++;$('#clock').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}},1000);$('#pause').onclick=()=>{running=!running;$('#pause').textContent=running?'Pausar':'Continuar'};$('#finish').onclick=()=>{clearInterval(id);let m=Math.max(1,Math.round(seconds/60));s.minutes=(s.minutes||0)+m;s.sessions=[...(s.sessions||[]),{id:crypto.randomUUID(),topic:'Sessao livre',minutes:m,date:new Date().toISOString()}];persist();closeModal();detail()}}
async function askAI(s){
  const q=$('#question').value.trim()||'Analisa o meu estado atual e recomenda o melhor próximo passo.';
  const agent=$('#aiAction').value;
  s.aiHistory=[...(s.aiHistory||[]),{role:'user',text:q,date:new Date().toISOString()}];recalc(s);renderTab(s,'ai');
  const out=$('#aiOut');out.innerHTML='<p class="muted">A analisar o teu contexto...</p>';
  try{
    const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agent,skill:{...s,aiHistory:undefined},question:q,history:s.aiHistory})});
    const d=await r.json();if(!r.ok)throw Error(d.error||'Erro');
    s.aiHistory=[...s.aiHistory,{role:'assistant',text:d.text,date:new Date().toISOString(),agent}];s.aiProposal=d.proposal||null;recalc(s);renderTab(s,'ai');
  }catch(e){s.aiHistory=[...s.aiHistory,{role:'assistant',text:`Não foi possível usar a IA: ${e.message}`,date:new Date().toISOString()}];recalc(s);renderTab(s,'ai')}
}
function showProposal(s,p){const out=$('#aiOut');if(!out||!p)return;const groups=[['roadmap','Roadmap'],['topics','Temas'],['practices','Práticas'],['assessments','Avaliações']].filter(([k])=>Array.isArray(p[k])&&p[k].length);if(!groups.length)return;out.innerHTML=`<div class="proposal"><b>Proposta estruturada</b><p class="muted">Revê antes de aplicar.</p>${groups.map(([k,l])=>`<div><b>${l}</b><div>${p[k].map(x=>`<span class="badge">${esc(x)}</span>`).join('')}</div></div>`).join('')}<div class="actions"><button id="rejectProposal" class="btn ghost">Rejeitar</button><button id="applyProposal" class="btn">Aplicar proposta</button></div></div>`;$('#rejectProposal').onclick=()=>{s.aiProposal=null;recalc(s);renderTab(s,'ai')};$('#applyProposal').onclick=()=>{groups.forEach(([k])=>{const existing=new Set((s[k]||[]).map(x=>x.title.toLowerCase()));s[k]=[...(s[k]||[]),...p[k].filter(x=>!existing.has(x.toLowerCase())).map(title=>({id:crypto.randomUUID(),title,done:false}))]});s.aiProposal=null;recalc(s);renderTab(s,'ai')};
}
function showModal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modal"><div class="card">${html}</div></div>`);$$('.close').forEach(b=>b.onclick=closeModal)}function closeModal(){$('.modal')?.remove()}
function bindCommon(){$$('[data-nav]').forEach(b=>b.onclick=()=>{state.view=b.dataset.nav;state.selected=null;render()});$$('[data-open]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.open;detail()});$('#new')&&($('#new').onclick=()=>form())}
render();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');